config/routes.rb
Spina::Engine.routes.draw do
  namespace :shop, path: '' do
    namespace :admin, path: Spina.config.backend_path do
      scope '/shop' do
        resources :shifts, only: [:index, :show]
      end
    end
  end
end

Spina::Pos::Engine.routes.draw do
  get :login, to: 'sessions#new'
  post :login, to: 'sessions#create', as: 'post_login'
  get :logout, to: 'sessions#destroy'

  resources :orders, only: [:new, :index, :show, :update] do
    resources :order_items, only: [:destroy]

    collection do
      post :add_product, format: :js
      post :add_product_bundle, format: :js
      get :scanned
      get :gift_card
      get :discount
      post :add_gift_card
      post :add_discount
      delete :remove_gift_card
      delete :remove_discount
    end
  end

  resources :products, only: [:index, :show] do
    collection do
      post :search
    end
  end

  resources :product_categories, only: [:show]
  resources :product_collections, only: [:index, :show]
  resources :product_bundles

  resources :checkout do
    collection do
      patch :update
      post :confirm
      get :cash_payment
      get :pin_payment
      get :finished
    end
  end
  resource :settings do
    resource :printer
    resources :orders do
      member do
        get :print
      end
    end
    resources :shifts
  end
end

app/models/spina/pos/cash_adjustment.rb
module Spina
  module Pos
    class CashAdjustment < ApplicationRecord
      belongs_to :shift

      # A positive amount is an addition, a negative amount a subtraction
      validates :amount, presence: true
    end
  end
end

app/models/spina/pos/preferences.rb
module Spina
  module Pos
    class Preferences < ApplicationRecord
      self.table_name = "spina_pos_preferences"

      belongs_to :user
      
      validates :user_id, presence: true, uniqueness: true
    end
  end
end

app/models/spina/pos/shift.rb
module Spina
  module Pos
    class Shift < ApplicationRecord
      belongs_to :user
      # has_many :cash_adjustments, dependent: :destroy
      has_many :orders, class_name: "Spina::Shop::Order", dependent: :restrict_with_exception

      validates :start_datetime, :opening_balance, presence: true

      validates :opening_balance, :cash_counted, :cash_left, numericality: true

      scope :open_shift, -> { where(end_datetime: nil) }
      scope :closed, -> { where.not(end_datetime: nil) }
      scope :ordered, -> { order(start_datetime: :desc) }

      def open?
        !closed?
      end

      def closed?
        end_datetime.present?
      end

      def current_balance
        opening_balance + orders.paid.sum(:total_cash)
      end

      def cash_difference
        cash_counted - cash_expected
      end

      def close_shift(cash_counted:, cash_left:, note:)
        update_attributes(
          cash_counted: cash_counted, 
          cash_left: cash_left, 
          cash_expected: current_balance, 
          end_datetime: Time.zone.now,
          note: note
        )
      end
    end
  end
end

app/controllers/spina/pos/checkout_controller.rb
module Spina::Pos
  module Errors
    class CurrentShiftNotFound < StandardError; end
  end
end

module Spina
  module Pos
    class CheckoutController < PosController
      before_action :set_order, except: [:finished]
      before_action :raise_exception_if_empty_order, except: [:finished]
      before_action :raise_exception_if_no_active_shift

      rescue_from Errors::CurrentShiftNotFound, with: :render_shift_instructions
      rescue_from Shop::Errors::EmptyOrder, with: :render_empty_order

      def index
      end

      def update
        @order.update_attributes(order_params)
      end

      def confirm
        @received = BigDecimal.new(params[:payment_received].gsub(",", "."))
        if @received >= @order.to_be_paid || (@order.payment_method == 'cash' && @received >= @order.to_be_paid_round)
          @order.shift = current_shift
          @order.transition_to!(:confirming)
          @order.transition_to!(:received)
          @order.transition_to!(:paid)
          @order.transition_to!(:picked_up)
          @change = @received - @order.to_be_paid_round if @order.payment_method == 'cash'
        else
          render :not_confirmed
        end
      rescue Exception => e
        Rails.logger.info @order.pos.inspect
        Rails.logger.info @order.everything_valid?.inspect
        Rails.logger.info @order.order_items.any?.inspect
        Rails.logger.info @order.errors.full_messages
        Rails.logger.info e
        render :not_confirmed
      ensure
        session[:order_id] = nil
      end

      def cash_payment
      end

      def pin_payment
      end

      def finished
        @change = BigDecimal.new(params[:change]) if params[:change].present?
      end

      private

        def raise_exception_if_no_active_shift
          raise Errors::CurrentShiftNotFound unless current_shift
        end

        def raise_exception_if_empty_order
          raise Shop::Errors::EmptyOrder unless @order.order_items.any?
        end

        def render_shift_instructions
          render 'shift_instructions'
        end

        def render_empty_order
          render 'empty_order'
        end

        def set_order
          @order = current_order
        end

        def order_params
          params.require(:order).permit(:payment_method)
        end

    end
  end
end

app/controllers/spina/pos/order_items_controller.rb
module Spina
  module Pos
    class OrderItemsController < PosController
      before_action :set_order

      def destroy
        @order_item = @order.order_items.find(params[:id])
        @order_item.destroy && @order.save
      end

      private

        def set_order
          @order = current_order
        end
    end
  end
end

app/controllers/spina/pos/orders_controller.rb
module Spina
  module Pos
    class OrdersController < PosController

      def new
        @order = current_order
        @order_items = @order.order_items.includes(:orderable).order(created_at: :desc)
      end

      def index
        @orders = Shop::Order.where(pos: true).received.order('received_at DESC').page(params[:page]).per(20)
      end

      def show
        @order = Shop::Order.find(params[:id])
      end

      def print
        @order = Shop::Order.find(params[:id])
      end

      def add_product
        # Raise order not building anymore if not building!
        product = Shop::Product.find(params[:product_id])

        @order_item = current_order.order_items.where(orderable: product).first_or_initialize
        @order_item.quantity = @order_item.quantity + 1
        @order_item.save && current_order.save
      rescue ActiveRecord::RecordNotFound 
        render :failed_to_add
      end

      def add_product_bundle
        product_bundle = Shop::ProductBundle.find(params[:product_bundle_id])

        @order_item = current_order.order_items.where(orderable: product_bundle).first_or_initialize
        @order_item.quantity = @order_item.quantity + 1
        @order_item.save && current_order.save
      rescue ActiveRecord::RecordNotFound
        render :failed_to_add
      end

      def scanned
        # Raise order not building anymore if not building!
        @order = current_order
        product_scan = params[:scan]
        item = Shop::Product.find_by!(ean: product_scan)
        @order_item = current_order.order_items.where(orderable: item).first_or_initialize
        @order_item.quantity = @order_item.quantity + 1
        @order_item.save && current_order.save
        render :add_product
      rescue ActiveRecord::RecordNotFound
        render :failed_to_add
      end

      def update
        # Raise order not building anymore if not building!
        @order = current_order
        @order.update_attributes(order_params)
      end

      def gift_card
        # Raise order not building anymore if not building!
        @order = current_order
      end

      def add_gift_card
        # Raise order not building anymore if not building!
        code = params[:gift_card].gsub(/\s|-/, "")
        gift_card = Shop::GiftCard.available.where(code: code).first

        if gift_card.present? && current_order.building?
          current_order.gift_card = gift_card
          current_order.save
        else
          render :failed_to_add_gift_card
        end
      end

      def remove_gift_card
        # Raise order not building anymore if not building!
        if current_order.building?
          current_order.gift_card = nil
          current_order.save
        end
      end

      def discount
        # Raise order not building anymore if not building!
        @order = current_order
      end

      def add_discount
        # Raise order not building anymore if not building!
        discount = Shop::Discount.where(code: params[:discount]).first

        if discount.present? && discount.active? && current_order.building?
          current_order.discount = discount
          current_order.save
        else
          render :failed_to_add_discount
        end
      end

      def remove_discount
        # Raise order not building anymore if not building!
        if current_order.building?
          current_order.discount = nil
          current_order.save
        end
      end

      private

        def order_params
          params.require(:order).permit(order_items_attributes: [:id, :quantity])
        end

    end
  end
end

app/controllers/spina/pos/pos_controller.rb
module Spina
  module Pos
    class PosController < ActionController::Base
      before_action :authorize
      protect_from_forgery with: :exception

      private

        def current_user
          @current_user ||= User.where(id: cookies.signed[:user_id]).first if cookies.signed[:user_id]
        end
        helper_method :current_user

        def pos_preferences
          @pos_preferences ||= Preferences.where(user_id: @current_user.id).first_or_create
        end
        helper_method :pos_preferences

        def pos_customer
          @pos_customer ||= Shop::Customer.where(first_name: 'POS', last_name: 'SmokeSmarter', email: 'info@smokesmarter.nl', store: Shop::Store.find_by(name: "SmokeSmarter"), country: Shop::Country.find_by(code: "NL")).first_or_create
        end
        helper_method :pos_customer

        def current_shift
          @current_shift ||= Shift.open_shift.ordered.where(user: current_user).first
        end
        helper_method :current_shift

        def current_order
          @current_order ||= begin
            if has_order?
              @current_order
            else
              order = Shop::Order.where(store: Shop::Store.find_by(name: "SmokeSmarter"), customer: pos_customer, user_id: current_user.id, received_at: nil, pos: true, billing_country: Shop::Country.find_by(code: "NL"), prices_include_tax: true).order(created_at: :desc).first_or_create
              session[:order_id] = order.id
              order
            end
          end
        end
        helper_method :current_order

        def has_order?
          session[:order_id] && @current_order = Shop::Order.where(pos: true).find_by_id(session[:order_id])
        end
        helper_method :has_order?

        def authorize
          head 401 unless current_user
        end
    end
  end
end

app/controllers/spina/pos/printers_controller.rb
module Spina
  module Pos
    class PrintersController < PosController

      def show
      end

      def update
        pos_preferences.update_attributes(pos_preferences_params)
      end

      private

        def pos_preferences_params
          params.require(:preferences).permit(:printer_ip)
        end

    end
  end
end

app/controllers/spina/pos/product_bundles_controller.rb
module Spina
  module Pos
    class ProductBundlesController < PosController

      def index
        @product_bundles = Shop::ProductBundle.all
      end

      def show
        @product_bundle = Shop::ProductBundle.find(params[:id])
      end

    end
  end
end

app/controllers/spina/pos/product_categories_controller.rb
module Spina
  module Pos
    class ProductCategoriesController < PosController

      def show
        @product_category = Shop::ProductCategory.find(params[:id])
        @products = @product_category.products.includes(:product_images).order(created_at: :desc).page(params[:page]).per(20)

        respond_to do |format|
          format.html
          format.js { render template: 'spina/pos/products/index' }
        end
      end

    end
  end
end

app/controllers/spina/pos/product_collections_controller.rb
module Spina
  module Pos
    class ProductCollectionsController < PosController

      def index
        @product_collections = Shop::ProductCollection.all
        @product_categories = Shop::ProductCategory.order(:name)
      end

      def show
        @product_collection = Shop::ProductCollection.find(params[:id])
        @products = @product_collection.products.includes(:product_images).order(:name).page(params[:page]).per(20)

        respond_to do |format|
          format.html
          format.js { render template: 'spina/pos/products/index' }
        end
      end

    end
  end
end

app/controllers/spina/pos/products_controller.rb
module Spina
  module Pos
    class ProductsController < PosController

      def index
        @products = Shop::Product.active.roots.includes(:product_images).order(created_at: :desc).page(params[:page]).per(20)
        @products = @products.search(params[:search]) if params[:search].present?
      end

      def show
        @product = Shop::Product.where(archived: false).find(params[:id])
      end

      def search
        @products = Shop::Product.active.roots.includes(:product_images).page(params[:page]).per(20)
        @products = @products.search(params[:search]) if params[:search].present?
      end

    end
  end
end

app/controllers/spina/pos/sessions_controller.rb
module Spina
  module Pos
    class SessionsController < PosController
      skip_before_action :authorize, only: [:new, :create]

      def new
      end

      def create
        user = User.where(email: params[:email]).first
        if user && user.authenticate(params[:password])
          cookies.signed.permanent[:user_id] = user.id
          user.update_last_logged_in!
          redirect_to spina_pos.products_url
        else
          flash.now[:alert] = I18n.t('spina.notifications.wrong_username_or_password')
          render "new"
        end
      end

      def destroy
        cookies.delete(:user_id)
        head 401
      end

    end
  end
end

app/controllers/spina/pos/settings_controller.rb
module Spina
  module Pos
    class SettingsController < PosController
      def show
        
      end
    end
  end
end

app/controllers/spina/pos/shifts_controller.rb
module Spina
  module Pos
    class ShiftsController < PosController
      before_action :check_current_shift, only: [:new, :create]

      def new
        @opening_balance = Shift.where(user_id: current_user.id).closed.ordered.first.try(:cash_left) || BigDecimal(0)
        @shift = Shift.new(opening_balance: @opening_balance)
      end

      def create
        @shift = Shift.new(shift_params)

        if @shift.save
          render js: "Turbolinks.visit('/turbolinks/back');"
        else
          render :new
        end
      end

      def edit
        @shift = current_shift
        @expected_balance = @shift.current_balance
      end

      def update
        @shift = current_shift

        if @shift.close_shift(cash_counted: close_params[:cash_counted], cash_left: close_params[:cash_left], note: close_params[:note])
          render js: "Turbolinks.visit('/turbolinks/back');"
        else
          render :edit
        end
      end

      private

        def check_current_shift
          raise Exception if current_shift.present?
        end

        def shift_params
          params.require(:shift).permit(:opening_balance).delocalize({opening_balance: :number}).merge(user_id: current_user.id, start_datetime: Time.zone.now)
        end

        def close_params
          params.require(:shift).permit(:cash_counted, :cash_left, :note).delocalize({cash_counted: :number, cash_left: :number})
        end

    end
  end
end

app/helpers/spina/pos/pos_helper.rb
module Spina
  module Pos
    module PosHelper

      def image_variant(image, variant, fallback: nil)
        if image&.file&.attached?
          main_app.url_for(image.file.variant(variant))
        else
          fallback || ""
        end
      rescue
        ""
      end
      
    end
  end
end

app/views/spina/pos/orders/_cart.html.haml
= form_for @order, data: {remote: true} do |f|
  = f.fields_for :order_items, @order_items do |ff|
    - unless ff.object.orderable == Spina::Shop::Product.find_by(sku: "statiegeld") || ff.object.orderable.nil?
      .cart-order-item-container
        .cart-order-item{data: {order_item_price: ff.object.unit_price, stock_level: ff.object.orderable.stock_level}}
          %span.order-item-price{style: 'float: right'}
            - if ff.object.discount_amount > 0
              %div{style: 'text-decoration: line-through; opacity: .5'}= number_to_currency ff.object.total_without_discount
              .text-green= number_to_currency ff.object.total
            - else
              = number_to_currency ff.object.total

          .select-container
            = ff.select :quantity, options_for_select((1..99).map{|i| ["#{i} &times;".html_safe, i]}, ff.object.quantity)
          = ff.object.description
          - if ff.object.is_product? && ff.object.orderable.variant?
            = ff.object.orderable.variant_name
          - if !ff.object.is_product_bundle? && ff.object.orderable.stock_enabled?
            %div.not-in-stock-message{style: ('display: none' if ff.object.orderable.stock_level >= ff.object.quantity)} 
              #{ff.object.orderable.stock_level} op voorraad

        = link_to '#', class: 'delete-item', data: {delete_path: order_order_item_path(@order.id, ff.object.id)} do
          = image_tag 'spina/pos/delete-pos.png', width: 24, height: 24

  - if @order.gift_card.present?
    .cart-order-item-container
      .cart-order-item
        %span.order-item-price{style: 'float: right'}
          \-
          = number_to_currency @order.gift_card_amount
        Cadeaubon
        = number_to_currency @order.gift_card.value
      = link_to '#', class: 'delete-item', data: {delete_path: remove_gift_card_orders_path} do
        = image_tag 'spina/pos/delete-pos.png', width: 24, height: 24

  - if @order.discount.present?
    .cart-order-item-container
      .cart-order-item= @order.discount.description
      = link_to '#', class: 'delete-item', data: {delete_path: remove_discount_orders_path} do
        = image_tag 'spina/pos/delete-pos.png', width: 24, height: 24

app/views/spina/pos/orders/_order.html.haml
%li 
  = link_to settings_order_path(order) do
    .pull-right{style: 'text-align: right'}
      = number_to_currency order.total
      %br/
      %small.text-muted
        - if order.order_items.sum(:quantity) == 1
          1 product
        - else
          = order.order_items.sum(:quantity)
          producten
    %strong=l order.received_at, format: '%H:%M'
    %br/
    %small.text-muted
      =l order.received_at, format: '%d %B'
      –
      = order.number

app/views/spina/pos/orders/add_discount.js.erb
webkit.messageHandlers.spina.postMessage("refresh_cart");

app/views/spina/pos/orders/add_gift_card.js.erb
webkit.messageHandlers.spina.postMessage("refresh_cart");

app/views/spina/pos/orders/add_product_bundle.js.erb
createjs.Sound.play(window.soundScanner);
webkit.messageHandlers.spina.postMessage("refresh_cart");

app/views/spina/pos/orders/discount.html.haml
- content_for(:title) { "Kortingscode" }

= form_for @order, url: add_discount_orders_path, method: :post, html: {id: 'order_discount_form'}, data: {remote: true} do |f|
  = f.submit 'Save', style: 'display: none'

  %div{style: 'margin-top: 40px'}

  = label_tag :discount, 'Code', class: 'form-label'

  .form-group
    .form-input-message.form-input-message-error
    .form-select-container
      = select_tag :discount, options_for_select(Spina::Shop::Discount.multiple_use.to_a.keep_if{|d| d.active?}.map{|d| [d.description + " (#{d.code})", d.code]}, @order.discount.try(:code)), prompt: "Kies een kortingscode"

app/views/spina/pos/orders/failed_to_add.js.erb
createjs.Sound.play(window.soundError);

app/views/spina/pos/orders/failed_to_add_gift_card.js.erb
$('form#order_gift_card_form .form-input-message').text("Code ongeldig");

app/views/spina/pos/orders/index.html.haml
- content_for(:title) { "Vorige bestellingen" }

%nav.list.order-overview
  %ul
    = render partial: 'order', collection: @orders

.order-pagination= link_to_next_page @orders, '', data: {remote: true}

app/views/spina/pos/orders/index.js.erb
$("<%=j render partial: 'order', collection: @orders %>").appendTo(".order-overview ul");
$('.order-pagination').html("<%= j link_to_next_page @orders, '', data: {remote: true} %>").infiniteScroll();

app/views/spina/pos/orders/new.html.haml
- content_for(:title) { "Winkelmand" }

.shopping-cart
  = text_field_tag :hoi, nil, style: 'width: 0px; overflow: hidden; min-width: 0px; -webkit-transform: scale(0); position: absolute'

  .scandieshit
    = link_to '#', id: 'start_scanning', class: 'btn' do
      = image_tag 'spina/pos/scannen.png', width: 141, height: 24

    .siriwave#siriwave

  #cart{style: 'padding-bottom: 50px'}= render partial: 'cart'

app/views/spina/pos/orders/new.js.erb
$("#cart").html("<%=j render 'cart' %>");

app/views/spina/pos/orders/print.js.erb
var printer = new Spina.PosPrinter("<%= pos_preferences.printer_ip %>", "<%= current_user.name %>");

<% @order.order_items.each do |order_item| %>
  printer.addOrderItem("<%= order_item.quantity %>", "<%=j order_item.description %>", "<%= number_to_currency(order_item.total) %>");
<% end %>

<% @order.tax_amount_by_rates.each do |rate| %>
  printer.addTaxLine("<%= number_to_human(rate[0]) %>", "<%= number_to_currency(rate[1][:tax_amount]) %>");
<% end %>

<% if @order.gift_card.present? %>
  printer.addGiftCard("<%= number_to_currency(@order.gift_card_amount) %>", "<%= number_to_currency(@order.to_be_paid) %>")
<% end %>

printer.setTotals("<%= number_to_currency(@order.order_total) %>", "<%= number_to_currency(@order.total) %>");

printer.setOrderNumber("#<%= @order.number %>");
printer.setReceivedAt("<%=l @order.received_at, format: "%d %B %Y %H:%M" %>");

printer.setPaymentMethod("<%=j @order.payment_method %>");

printer.print({openDrawer: false});